USER-SUPPLIED VALUES:
image:
  digest: sha256:6544a3441b086a2e09005d3e21d1a4afb216fae19c5a60b35793c8a9438f8f68
  tag: v1.13.0
bpf:
  masquerade: true
hubble:
  enabled: true
  metrics:
    enabled:
    - dns
    - drop
    - tcp
    - flow
    - port-distribution
    - icmp
    - http
  relay:
    enabled: true
  tls:
    auto:
      enabled: true
      method: helm
  ui:
    enabled: true
    ingress:
      class: nginx
      enabled: false
      hosts:
        - hubble.sreplayground.local
image:
  pullPolicy: IfNotPresent
ipMasqAgent:
  enabled: true
ipam:
  mode: kubernetes
k8sServiceHost: sre-demo-site-control-plane
k8sServicePort: 6443
kubeProxyReplacement: strict
operator:
# -- Enable prometheus metrics for cilium-operator on the configured port at /metrics
  prometheus:
    enabled: true
# -- Enable prometheus metrics for cilium-operator on the configured port at /metrics
prometheus:
  enabled: true
# -- Cilium Ingress is disabled using nginx ingress controller. Cilium ingress controller 
#    is no compatible with kind clusters
ingressController:
  enabled: false
  loadbalancerMode: shared
