loki:
  enabled: true
  isDefault: true
  url: http://{{(include "loki.serviceName" .)}}:{{ .Values.loki.service.port }}
  image:
    tag: "2.6.1"
prometheus:
  enabled: false
filebeat:
  enabled: false
logstash:
  enabled: false
promtail:
  enabled: false
fluent-bit:
  enabled: false
grafana:
  enabled: false
