apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-java-instrumentation
  namespace: {{ default "app" .Values.namespace | quote }}
spec:
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.19.1
  exporter:
    endpoint: http://localhost:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1.00"
