apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-sidecar-service
  namespace: {{ default "app" .Values.namespace | quote }}
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
    exporters:
      logging:
      otlp:
        endpoint: otel-local-service-collector:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [logging,otlp]
