components:
  accountingService:
    enabled: true
  adService:
    enabled: true
  cartService:
    enabled: true
  checkoutService:
    enabled: true
  currencyService:
    enabled: true
  emailService:
    enabled: true
  featureflagService:
    enabled: true
  ffsPostgres:
    enabled: true
  frauddetectionService:
    enabled: true
  frontend:
    enabled: true
    env:
    - name: FRONTEND_ADDR
      value: :8080
    - name: AD_SERVICE_ADDR
      value: '{{ include "otel-demo.name" . }}-adservice:8080'
    - name: CART_SERVICE_ADDR
      value: '{{ include "otel-demo.name" . }}-cartservice:8080'
    - name: CHECKOUT_SERVICE_ADDR
      value: '{{ include "otel-demo.name" . }}-checkoutservice:8080'
    - name: CURRENCY_SERVICE_ADDR
      value: '{{ include "otel-demo.name" . }}-currencyservice:8080'
    - name: PRODUCT_CATALOG_SERVICE_ADDR
      value: '{{ include "otel-demo.name" . }}-productcatalogservice:8080'
    - name: RECOMMENDATION_SERVICE_ADDR
      value: '{{ include "otel-demo.name" . }}-recommendationservice:8080'
    - name: SHIPPING_SERVICE_ADDR
      value: '{{ include "otel-demo.name" . }}-shippingservice:8080'
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://$(OTEL_COLLECTOR_NAME):4317
    - name: WEB_OTEL_SERVICE_NAME
      value: frontend-web
    - name: FRONTEND_PORT
      value: "8080"
    - name: PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      value: http://otel.sreplayground.local/v1/traces
  frontendProxy:
    enabled: true
  kafka:
    enabled: true
  loadgenerator:
    enabled: true 
  paymentService:
    enabled: true
  productCatalogService:
    enabled: true
  quoteService:
    enabled: true
  recommendationService:
    enabled: true
  redis:
    enabled: true
  shippingService:
    enabled: true
observability:
  grafana:
    enabled: false # The demo is using another grafana instance from prometheus community
  jaeger:
    enabled: true
  otelcol:
    enabled: true
  prometheus:
    enabled: false # The demo is using another prometheus instance from prometheus community
opentelemetry-collector:
  config:
    service:
      pipelines:
        metrics:
          exporters:
            - prometheus
        traces:
          exporters:
            - otlp