storage:
  type: elasticsearch
  elasticsearch:
    host: elasticsearch-es-http.elasticsearch.svc
    port: 9200
    scheme: https
    user: elastic
    password: changeit
provisionDataStore:
  cassandra: false
  elasticsearch: false
query:
  cmdlineParams:
    es.tls.enabled: true
    es.tls.ca: /tls/ca.crt
    es.tls.cert: /tls/tls.crt
    es.tls.key: /tls/tls.key
  extraConfigmapMounts:
    - name: jaeger-tls
      mountPath: /tls
      subPath: ""
      configMap: jaeger-tls
      readOnly: true
collector:
  cmdlineParams:
    es.tls.enabled: true
    es.tls.ca: /tls/ca.crt
    es.tls.cert: /tls/tls.crt
    es.tls.key: /tls/tls.key
  extraConfigmapMounts:
    - name: jaeger-tls
      mountPath: /tls
      subPath: ""
      configMap: jaeger-tls
      readOnly: true
spark:
  enabled: true
  cmdlineParams:
    java.opts: "-Djavax.net.ssl.trustStore=/tls/trust.store -Djavax.net.ssl.trustStorePassword=changeit"
  extraConfigmapMounts:
    - name: jaeger-tls
      mountPath: /tls
      subPath: ""
      configMap: jaeger-tls
      readOnly: true
