components:
  accountingService:
    enabled: true
  adService:
    enabled: true
  cartService:
    enabled: true
  checkoutService:
    enabled: true
  currencyService:
    enabled: true
  emailService:
    enabled: true
  featureflagService:
    enabled: true
  ffsPostgres:
    enabled: true
  frauddetectionService:
    enabled: true
  frontend:
    enabled: true
  frontendProxy:
    enabled: true
  kafka:
    enabled: true
  loadgenerator:
    enabled: true 
  paymentService:
    enabled: true
  productCatalogService:
    enabled: true
  quoteService:
    enabled: true
  recommendationService:
    enabled: true
  redis:
    enabled: true
  shippingService:
    enabled: true
observability:
  grafana:
    enabled: false # The demo is another grafana instance
  jaeger:
    enabled: true
  otelcol:
    enabled: true
  prometheus:
    enabled: false # The demo is another prometheus instance
opentelemetry-collector:
  config:
    service:
      pipelines:
        metrics:
          exporters:
            - prometheus
        traces:
          exporters:
            - otlp