components:
  featureflagService:
    enabled: false
grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - editable: true
        isDefault: true
        name: Prometheus
        type: prometheus
        uid: webstore-metrics
        url: http://{{ include "otel-demo.name" . }}-prometheus-server:9090
      - editable: true
        isDefault: false
        name: Jaeger
        type: jaeger
        uid: webstore-traces
        url: http://{{ include "otel-demo.name" . }}-jaeger-query:16686/jaeger/ui
      - name: Loki
        type: loki
        access: proxy
        url: "http://loki.loki-stack.svc:3100"
        version: 1
        isDefault: false
        jsonData:
          derivedFields:
          - datasourceUid: Jaeger
            matcherRegex: "trace_id=(\\w+)"
            name: TraceID
            url: "$${__value.raw}"