components:
  accountingService:
    enabled: true
  adService:
    enabled: true
  cartService:
    enabled: true
  checkoutService:
    enabled: true
  currencyService:
    enabled: true
  emailService:
    enabled: true
  featureflagService:
    enabled: true
  ffsPostgres:
    enabled: true
  frauddetectionService:
    enabled: true
  frontend:
    enabled: true
  frontendProxy:
    enabled: true
  kafka:
    enabled: true
  loadgenerator:
    enabled: true 
  paymentService:
    enabled: true
  productCatalogService:
    enabled: true
  quoteService:
    enabled: true
  recommendationService:
    enabled: true
  redis:
    enabled: true
  shippingService:
    enabled: true
prometheus:
  kube-state-metrics:
    enabled: true
  prometheus-node-exporter:
    enabled: true
  serverFiles:
    prometheus.yml:
      scrape_configs:
      - job_name: opentelemetry-community-demo
        kubernetes_sd_configs:
        - namespaces:
            own_namespace: true
          role: pod
        relabel_configs:
        - action: keep
          regex: true
          source_labels:
          - __meta_kubernetes_pod_annotation_opentelemetry_community_demo
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - editable: true
        isDefault: true
        name: Prometheus
        type: prometheus
        uid: webstore-metrics
        url: http://{{ include "otel-demo.name" . }}-prometheus-server:9090
      - editable: true
        isDefault: false
        name: Jaeger
        type: jaeger
        uid: webstore-traces
        url: http://{{ include "otel-demo.name" . }}-jaeger-query:16686/jaeger/ui
      - name: Loki
        type: loki
        access: proxy
        url: "http://loki.loki-stack.svc:3100"
        version: 1
        isDefault: false
        jsonData:
          derivedFields:
          - datasourceUid: Jaeger
            matcherRegex: "trace_id=(\\w+)"
            name: TraceID
            url: "$${__value.raw}"