alertmanager:
  alertmanagerSpec:
    image:
      tag: v0.25.0
grafana:
  image:
    tag: "9.3.6"
  adminPassword: prom-operator
  adminUser: admin
  additionalDataSources:
      - editable: false
        isDefault: false
        name: Jaeger
        type: jaeger
        uid: webstore-traces
        url: http://app-hipster-shop-jaeger-query.default.svc:16686/jaeger/ui
      - name: Loki
        editable: false
        type: loki
        access: proxy
        url: "http://loki.loki.svc:3100"
        version: 1
        isDefault: false
        jsonData:
          derivedFields:
          - datasourceUid: Jaeger
            matcherRegex: "trace_id=(\\w+)"
            name: TraceID
            url: "$${__value.raw}"
nodeExporter:
  enabled: true
prometheus:
  image:
    tag: "v2.42.0"
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: opentelemetry-community-demo
      static_configs:
      - targets:
        - 'app-hipster-shop-otelcol.default.svc:9464'
kube-state-metrics:
  image:
    tag: "v2.8.0"
prometheusOperator:
  image:
    tag: "v0.63.0"