# Default values for sreplayground.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cni:
  kindnet:
    enabled: true
  cilium: 
    enabled: false
cert-manager:
  enabled: true
  installCRDs: true
istio-base:
  enabled: true