# Default values for sreplayground.
# This is a YAML-formatted file.

cert-manager:
  enabled: true
  installCRDs: true

cilium:
  enabled: false # should be set to true via bootstrap script or manually pass usnig --set
  image:
    digest: sha256:6544a3441b086a2e09005d3e21d1a4afb216fae19c5a60b35793c8a9438f8f68
    tag: v1.13.0
  bpf:
    masquerade: true
  hubble:
    enabled: true
    metrics:
      enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
    relay:
      enabled: true
    tls:
      auto:
        enabled: true
        method: helm
    ui:
      enabled: true
      ingress:
        class: nginx
        className: nginx
        enabled: true
        hosts:
          - hubble.sre-playground.devops.nakednerds.net
  ipMasqAgent:
    enabled: true #dynamically set using bootstrap script
  ipam:
    mode: kubernetes
  k8sServiceHost: <dynamically set>
  k8sServicePort: 6443
  kubeProxyReplacement: strict #dynamically set using bootstrap script
  operator:
  # -- Enable prometheus metrics for cilium-operator on the configured port at /metrics
    prometheus:
      enabled: true
  # -- Enable prometheus metrics for cilium-operator on the configured port at /metrics
  prometheus:
    enabled: true
  # -- Cilium Ingress is disabled using nginx ingress controller. Cilium ingress controller 
  #    is no compatible with kind clusters
  ingressController:
    enabled: false
    loadbalancerMode: shared

metallb:
  enabled: true
  IPAddressPool: first-pool
  addresspool: <SET BY installer.sh or set manually>
  controller:
    image:
      tag: "v0.13.9"
  speaker:
    image:
      tag: "v0.13.9"

opentelemetry-collector:
  enabled: true
  mode: daemonset
  hostNetwork: false
  podLabels: 
    otel-component: agent-ds-collector
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: "Exists"
  config:
    exporters:
      logging: {}
      otlp:
        endpoint: 'sreplayground-platform-opentelemetry-collector.platform.svc.cluster.local:4317'
        tls: 
          insecure: true
    extensions:
      health_check: {}
      memory_ballast:
        size_in_percentage: 40
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: ${MY_POD_IP}:14250
          thrift_compact:
            endpoint: ${MY_POD_IP}:6831
          thrift_http:
            endpoint: ${MY_POD_IP}:14268
      otlp:
        protocols:
          grpc:
            endpoint: ${MY_POD_IP}:4317
          http:
            endpoint: ${MY_POD_IP}:4318
      prometheus:
        config:
          scrape_configs:
          - job_name: opentelemetry-collector
            scrape_interval: 10s
            static_configs:
            - targets:
              - ${MY_POD_IP}:8888
      zipkin:
        endpoint: ${MY_POD_IP}:9411
    service:
      extensions:
      - health_check
      - memory_ballast
      pipelines:
        traces:
          exporters:
          - logging
          - otlp
          processors:
          - memory_limiter
          - batch
          receivers:
          - otlp
      telemetry:
        metrics:
          address: ${MY_POD_IP}:8888
