apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: chaos-parallel-workflow
  namespace: chaos-mesh 
spec:
  entry: entry
  templates:
    - name: entry
      templateType: Serial
      deadline: 240s
      children:
        - workflow-stress-chaos
        - workflow-network-chaos
        - workflow-pod-chaos-schedule
    - name: workflow-network-chaos
      templateType: NetworkChaos
      deadline: 20s
      networkChaos:
        direction: to
        action: delay
        mode: all
        selector:
          namespaces:
          - 'default'
          labelSelectors:
            app.kubernetes.io/component: 'adservice'
        delay:
          latency: '90ms'
          correlation: '25'
          jitter: '90ms'
    - name: workflow-pod-chaos-schedule
      templateType: Schedule
      deadline: 40s
      schedule:
        concurrencyPolicy: 'Allow'
        schedule: '@every 2s'
        type: 'PodChaos'
        podChaos:
          action: pod-kill
          mode: one
          selector:
            namespaces:
            - 'default'
            labelSelectors:
              app.kubernetes.io/component: 'adservice'
    - name: workflow-stress-chaos
      templateType: StressChaos
      deadline: 20s
      stressChaos:
        mode: one
        selector:
          namespaces:
          - 'default'
          labelSelectors:
            app.kubernetes.io/component: 'adservice'
        stressors:
          cpu:
            workers: 1
            load: 20
            options: ['--cpu 1', '--timeout 600']