apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-sidecar-service
  namespace: {{ default "app" .Values.namespace | quote }}
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-metrics-collector'
            scrape_interval: 10s
            metrics_path: '/actuator/prometheus'
            static_configs:
            - targets: ['0.0.0.0:8080']
    exporters:
      logging:
      otlp:
        endpoint: otel-local-service-collector:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          exporters: [otlp]
