apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-root-issuer
spec:
  selfSigned: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: docker-registry
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docker-registry-ca
  namespace: docker-registry
spec:
  isCA: true
  commonName: docker-registry-ca
  secretName: docker-registry-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-cluster-root-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: docker-registry-ca-issuer
  namespace: docker-registry
spec:
  ca:
    secretName: docker-registry-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docker-registry-server-tls
  namespace: docker-registry
spec:
  commonName: docker-registry-server-tls
  secretName: docker-registry-server-tls
  dnsNames:
  - docker-registry.switch.com
  - localhost
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: docker-registry-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docker-registry-client-tls
  namespace: docker-registry
spec:
  commonName: docker-registry-client-tls
  secretName: docker-registry-client-tls
  dnsNames:
  - docker-registry.switch.com
  - localhost
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: docker-registry-ca-issuer
    kind: Issuer
    group: cert-manager.io