apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-root-issuer
spec:
  selfSigned: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: zot
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zot-ca
  namespace: zot
spec:
  isCA: true
  commonName: zot-ca
  secretName: zot-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-cluster-root-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: zot-ca-issuer
  namespace: zot
spec:
  ca:
    secretName: zot-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zot-server-tls
  namespace: zot
spec:
  commonName: zot-server-tls
  secretName: zot-server-tls
  dnsNames:
  - zot.switch.com
  - localhost
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: zot-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zot-client-tls
  namespace: zot
spec:
  commonName: zot-client-tls
  secretName: zot-client-tls
  dnsNames:
  - zot.switch.com
  - localhost
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: zot-ca-issuer
    kind: Issuer
    group: cert-manager.io