# Default values for playground.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ingress:
  enabled: false
  class: nginx
  className: "nginx"
  annotations: {}
  components:
  - name: hipstershop
    rules:
    # - http:
    #     paths:
    #     - path: /
    #       pathType: Prefix
    #       backend:
    #         service:
    #           name: sreplayground-hipstershop-frontendproxy
    #           port: 
    #             number: 8080
    #   host: "hipstershop.sre-playground.devops.nakednerds.net"
    - http:
        paths:
        - backend:
            service:
              name: sreplayground-hipstershop-otelcol
              port:
                number: 4318
          path: /v1/traces
          pathType: Prefix
      host: "otel.sre-playground.devops.nakednerds.net"
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: sreplayground-hipstershop-dark-index-page
              port: 
                number: 8080
      host: "sre-playground.devops.nakednerds.net"
opentelemetry-demo:
  enabled: true
  default:
    image:
      tag: "1.3.1"
  components:
    accountingService:
      enabled: true
    adService:
      enabled: true
    cartService:
      enabled: true
    checkoutService:
      enabled: true
    currencyService:
      enabled: true
    emailService:
      enabled: true
    featureflagService:
      enabled: true
    ffsPostgres:
      enabled: true
    frauddetectionService:
      enabled: true
    frontend:
      enabled: true
      env:
      - name: FRONTEND_ADDR
        value: :8080
      - name: AD_SERVICE_ADDR
        value: '{{ include "otel-demo.name" . }}-adservice:8080'
      - name: CART_SERVICE_ADDR
        value: '{{ include "otel-demo.name" . }}-cartservice:8080'
      - name: CHECKOUT_SERVICE_ADDR
        value: '{{ include "otel-demo.name" . }}-checkoutservice:8080'
      - name: CURRENCY_SERVICE_ADDR
        value: '{{ include "otel-demo.name" . }}-currencyservice:8080'
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: '{{ include "otel-demo.name" . }}-productcatalogservice:8080'
      - name: RECOMMENDATION_SERVICE_ADDR
        value: '{{ include "otel-demo.name" . }}-recommendationservice:8080'
      - name: SHIPPING_SERVICE_ADDR
        value: '{{ include "otel-demo.name" . }}-shippingservice:8080'
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://$(OTEL_COLLECTOR_NAME):4317
      - name: WEB_OTEL_SERVICE_NAME
        value: frontend-web
      - name: FRONTEND_PORT
        value: "8080"
      - name: PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        value: http://otel.{{ .Release.Name }}.devops.nakednerds.net/v1/traces
    frontendProxy:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts: 
        - host: hipstershop.devops.nakednerds.net
          paths:
          - path: /
            pathType: Prefix
            port: 8080
    kafka:
      enabled: true
    loadgenerator:
      enabled: true 
    paymentService:
      enabled: true
    productCatalogService:
      enabled: true
    quoteService:
      enabled: true
    recommendationService:
      enabled: true
    redis:
      enabled: true
    shippingService:
      enabled: true
  grafana:
    enabled: false # The demo is using another grafana instance from prometheus community
  jaeger:
    enabled: false
  prometheus:
    enabled: false # The demo is using another prometheus instance from prometheus community
  opentelemetry-collector:
    enabled: true
    config:
      exporters:
        otlp:
          endpoint: ""