---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hipstershop
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-hipster-shop-frontendproxy
            port: 
              number: 8080
    host: "demo.sre-playground.devops.nakednerds.net"
  - http:
      paths:
      - backend:
          service:
            name: app-hipster-shop-otelcol
            port:
              number: 4318
        path: /v1/traces
        pathType: Prefix
    host: "otel.sre-playground.devops.nakednerds.net"
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dark-index-page
            port: 
              number: 8080
    host: "sre-playground.devops.nakednerds.net"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-chaos-dashboard
  namespace: chaos-mesh
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chaos-dashboard
            port: 
              number: 2333
    host: "chaostest.sre-playground.devops.nakednerds.net"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: cilium
    meta.helm.sh/release-namespace: kube-system
  labels:
    app.kubernetes.io/name: hubble-ui
    k8s-app: hubble-ui
  name: hubble-ui
  namespace: kube-system
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: hubble-ui
            port:
              name: http
        path: /
        pathType: Prefix
    host: "hubble.sre-playground.devops.nakednerds.net"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-prometheus
  namespace: prometheus
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: prometheus-kube-prometheus-prometheus
              port: 
                number: 9090
      host: "prometheus.sre-playground.devops.nakednerds.net"
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: prometheus-grafana
              port: 
                number: 80
      host: "grafana.sre-playground.devops.nakednerds.net"
