COMPUTED VALUES:
logLevel: info
metricsPort: 2020
flush: 1
image:
  tag: "2.0.9"
config:
  customParsers: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  extraFiles: 
    labelmap.json: |-
      {
        "kubernetes": {
          "container_name": "container",
          "host": "node",
          "labels": {
            "app": "app",
            "app.kubernetes.io/name": "job"
          },
          "namespace_name": "namespace",
          "pod_name": "instance"
        },
        "stream": "stream"
      }
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Kube_URL https://kubernetes.default.svc:443
        Merge_Log On
        Keep_Log On
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On
  outputs: |
    [Output]
        Name loki
        host loki.loki
        port 3100
        http_user admin
        http_passwd admin
        Match kube.*
        labels job=kubernetes
        label_map_path /fluent-bit/etc/labelmap.json
        remove_keys kubernetes,stream
  service: |
    [SERVICE]
        Daemon Off
        Flush {{ .Values.flush }}
        Log_Level {{ .Values.logLevel }}
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.metricsPort }}
        Health_Check On
  upstream: {}
tolerations:
- key: node-role.kubernetes.io/control-plane
  operator: "Exists"