apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
spec:
  version: {{ .Values.ES_VERSION }}
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false