---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  namespace: {{ default "app" .Values.namespace | quote }}
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
      # annotations:
      #    sidecar.opentelemetry.io/inject: "true"
      #    instrumentation.opentelemetry.io/inject-java: "true"
      #    instrumentation.opentelemetry.io/container-names: "server"
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      # securityContext:
      #   fsGroup: 1000
      #   runAsGroup: 1000
      #   runAsNonRoot: true
      #   runAsUser: 1000
      containers:
        - name: server
          # securityContext:
          #   allowPrivilegeEscalation: false
          #   capabilities:
          #     drop:
          #       - all
          #   privileged: false
          #   readOnlyRootFilesystem: false #changed from true
          #image: gcr.io/google-samples/microservices-demo/adservice:v0.4.0
          image: gcr.io/google-samples/microservices-demo/adservice:v0.4.1
          #image: gcr.io/google-samples/microservices-demo/adservice:v0.4.1-native-grpc-probes
          ports:
            - containerPort: 9555
          env:
            - name: PORT
              value: "9555"
            - name: DISABLE_STATS
              value: "0"
            - name: DISABLE_TRACING
              value: "0"
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 30
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9555"]
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 30
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:9555"]
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: {{ default "app" .Values.namespace | quote }}
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
    - name: grpc
      port: 9555
      targetPort: 9555
