{{- if .Values.metallb.enabled }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Release.Name }}-{{ .Values.metallb.IPAddressPool }}
  annotations:
    helm.sh/hook: post-install, post-upgrade
spec:
  addresses:
    - {{ .Values.metallb.addresspool }}

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Release.Name }}-l2advertisement
  annotations:
    helm.sh/hook: post-install, post-upgrade
spec:
  ipAddressPools:
    - {{ .Release.Name }}-{{ .Values.metallb.IPAddressPool }}
{{- end }}