{{- if index .Values "opentelemetry-collector" "enabled" }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: opentelemetry-collector
    app.kubernetes.io/instance: {{ .Release.Name }}-otel-agent-service
    app.kubernetes.io/managed-by: opentelemetry-operator
    app.kubernetes.io/name: {{ .Release.Name }}-otel-agent-service
    app.kubernetes.io/part-of: opentelemetry
    app.kubernetes.io/version: latest
  name: otel-collector
  namespace: kube-system
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: grpc
    name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  selector:
    component: agent-collector
    otel-component: agent-ds-collector
  sessionAffinity: None
  type: ClusterIP

{{- end }}