{{ $releaseName := .Release.Name }}
{{ $releaseNamespace := .Release.Namespace }}
{{- if .Values.ingress.enabled }}
{{- range $key, $val := .Values.ingress.components }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $releaseName }}-{{ .name }}
  namespace: {{ $releaseNamespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules: {{ .rules | toYaml | nindent 4 }}

{{- end }}
{{- end }}