apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: {{ .Release.Name }}-jaeger
spec:
  strategy: allInOne
  allInOne:
    image: jaegertracing/all-in-one:latest
    options:
      log-level: debug
  storage:
    type: memory
    options:
      memory:
        max-traces: 100000
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
    - jaeger.{{ .Release.Name }}.devops.nakednerds.net
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
