apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ .Release.Name }}-opentelemetry
  # annotations:
  #   helm.sh/hook: post-install, post-upgrade
spec:
  hostNetwork: true
  mode: daemonset
  # tolerations:
  # - key: node-role.kubernetes.io/control-plane
  #   operator: "Exists"
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
    exporters:
      jaeger:
        endpoint: "sreplayground-app-jaeger-collector.app.svc:14250"   
        tls:
          insecure: true  
      logging:
      otlp:
        endpoint: otel-remote-service-collector.observability.svc.cluster.local:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers:
          - "otlp"
          exporters:
          - "logging"
          - "jaeger"