apiVersion: v1
kind: Secret
metadata:
  labels:
    app: thanos
  name: {{ .Release.Name }}-thanos-storage-connection-string
data:
  thanos.yaml: |-
{{ .Files.Get "files/thanos-storage-config.yaml" | b64enc | indent 4 }}